services:
  backend:
    build: .
    ports:
      - "8686:8686"
    volumes:
      - ouroboros-volume:/ouroboros-volume
    environment:
      - VOLUME_MOUNT_PATH=/ouroboros-volume
      - VOLUME_SERVER_URL=http://host.docker.internal:3001
    extra_hosts:
    - "host.docker.internal:host-gateway"
    shm_size: 1gb

volumes:
  ouroboros-volume:
    external: true
